<p style="font-family: Arial; font-size:3.75em;color:purple; font-style:bold"><br>
Introduction to numpy:
</p><br>

<p style="font-family: Arial; font-size:1.25em;color:#2462C0; font-style:bold"><br>
Package for scientific computing with Python
</p><br>

<p>This course has been prepared by Tamas Gal</p>

Numerical Python, or "Numpy" for short, is a foundational package on which many of the most common data science packages are built.  Numpy provides us with high performance multi-dimensional arrays which we can use as vectors or matrices.  

The key features of numpy are:

- ndarrays: n-dimensional arrays of the same data type which are fast and space-efficient.  There are a number of built-in methods for ndarrays which allow for rapid processing of data without using loops (e.g., compute the mean).
- Broadcasting: a useful tool which defines implicit behavior between multi-dimensional arrays of different sizes.
- Vectorization: enables numeric operations on ndarrays.
- Input/Output: simplifies reading and writing of data from/to file.

<b>Additional Recommended Resources:</b><br>
<a href="https://docs.scipy.org/doc/numpy/reference/">Numpy Documentation</a><br>
<i>Python for Data Analysis</i> by Wes McKinney<br>
<i>Python Data science Handbook</i> by Jake VanderPlas



In [2]:
import numpy as np
import sys

print("Python version: {0}\n"
      "NumPy version: {1}"
      .format(sys.version, np.__version__))

Python version: 3.6.10 |Anaconda, Inc.| (default, Jan  7 2020, 21:14:29) 
[GCC 7.3.0]
NumPy version: 1.18.1


In [3]:
def describe(np_obj):
    """Print some information about a NumPy object"""
    print("object type: {0}\n"
          "size: {o.size}\n"
          "ndim: {o.ndim}\n"
          "shape: {o.shape}\n"
          "dtype: {o.dtype}"
          .format(type(np_obj), o=np_obj))

In [4]:
from IPython.core.magic import register_line_magic

@register_line_magic
def shorterr(line):
    """Show only the exception message if one is raised."""
    try:
        output = eval(line)
    except Exception as e:
        print("\x1b[31m\x1b[1m{e.__class__.__name__}: {e}\x1b[0m".format(e=e))
    else:
        return output
    
del shorterr

## The basic datastructure in NumPy: `ndarray`

In [3]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [4]:
type(a)

numpy.ndarray

### Array properties

In [52]:
a.size  # number of elements

6

In [53]:
a.ndim # 1 dimension (vector)

1

In [5]:
a.shape 
a[1]='toto'

ValueError: invalid literal for int() with base 10: 'toto'

In [6]:
a.dtype # try to change one of the value to a string

dtype('int64')

### Array are mutable

In [64]:
b= np.array(['toto'])
b

array(['toto'], dtype='<U4')

In [8]:
print(id(a))
a[0]=6

print(id(a))

140658093067840
140658093067840


### Multi-Dimensional Arrays

In [10]:
b = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [11]:
describe(b)

object type: <class 'numpy.ndarray'>
size: 10
ndim: 2
shape: (2, 5)
dtype: int64


### Array Methods

In [70]:
a.min(), a.max(), a.mean(), a.sum()

(1, 6, 3.5, 21)

In [71]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [72]:
b.sum()

55

In [73]:
b.sum(axis=0)

array([ 7,  9, 11, 13, 15])

In [74]:
b.sum(axis=1)

array([15, 40])

## Operations with Arrays

In [75]:
a

array([2, 1, 3, 4, 5, 6])

In [76]:
a - 42

array([-40, -41, -39, -38, -37, -36])

In [77]:
a * 42 / np.pi

array([26.73803044, 13.36901522, 40.10704566, 53.47606088, 66.8450761 ,
       80.21409132])

In [78]:
a**np.e, np.e**a

(array([  6.58088599,   1.        ,  19.81299075,  43.30806043,
         79.43235917, 130.38703324]),
 array([  7.3890561 ,   2.71828183,  20.08553692,  54.59815003,
        148.4131591 , 403.42879349]))

In [79]:
a * a  # element-wise

array([ 4,  1,  9, 16, 25, 36])

In [80]:
a @ a  # use np.dot(a, a) if you are using < Python 3.5

91

In [81]:
a

array([2, 1, 3, 4, 5, 6])

In [82]:
a < 3

array([ True,  True, False, False, False, False])

In [83]:
a == 4

array([False, False, False,  True, False, False])

In [84]:
(a > 3) & (a < 5)  # bitwise AND

array([False, False, False,  True, False, False])

In [85]:
a < np.array([2, 3, 5, 2, 1, 5])

array([False,  True,  True, False, False, False])

In [87]:
np.sum(a > 2)

4

## Basic Indexing and Slicing

In [88]:
a[0]  # indexing starts at 0

2

In [89]:
a[-1]  # -1 refers to the last element

6

In [90]:
a[2:6:3]  # just like in Python: [start:end:step]

array([3, 6])

In [91]:
a[::-1]  # reversing an array

array([6, 5, 4, 3, 1, 2])

In [92]:
b[::-1]  # reverses axis 0

array([[ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

### Indixing and Slicing in Multiple Dimensions

In [93]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [94]:
b[0, 2]

3

In [95]:
b[0, 1:4]

array([2, 3, 4])

In [96]:
b[:, 1:4]  # the `:` selects the whole axis

array([[2, 3, 4],
       [7, 8, 9]])

In [97]:
b[:, 2:5:2]

array([[ 3,  5],
       [ 8, 10]])

In [98]:
b[::-1, ::-1]  # reverses both axes

array([[10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

### Advanced Indexing

In [99]:
d = np.array([4, 3, 2, 5, 4, 5, 4, 4])

In [100]:
mask = np.array([True, False, False, True, False, False, True, True])
mask

array([ True, False, False,  True, False, False,  True,  True])

In [101]:
d[mask]

array([4, 5, 4, 4])

In [102]:
d[[1, 3, 1, 6]]

array([3, 5, 3, 4])

#### Be careful with boolean indexing, the mask has to be a boolean array or a list of booleans.

In [103]:
d

array([4, 3, 2, 5, 4, 5, 4, 4])

In [104]:
d[[False, True, False, False, True, False, False, True]]

array([3, 4, 4])

In [105]:
d[[0, 1, 0, 0, 1, 0, 0, 1]]  # although we know that True==1 and False==0

array([4, 3, 4, 4, 3, 4, 4, 3])

In [106]:
d[np.array([0, 1, 0, 0, 1, 0, 0, 1], dtype=bool)] 

array([3, 4, 4])

## The `dtype`

In [107]:
np.dtype

numpy.dtype

In [108]:
a, a.dtype

(array([2, 1, 3, 4, 5, 6]), dtype('int64'))

In [109]:
e = a * 42 / np.pi  # NumPy will choose the "right" `dtype` automatically
e, e.dtype

(array([26.73803044, 13.36901522, 40.10704566, 53.47606088, 66.8450761 ,
        80.21409132]), dtype('float64'))

## Helper Functions to Create Arrays

In [110]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [111]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [112]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [113]:
np.zeros((2, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [114]:
np.empty(20)

array([2.10077583e-312, 2.05833592e-312, 2.18565567e-312, 2.33419537e-312,
       6.79038654e-313, 2.29175545e-312, 2.31297541e-312, 2.33419537e-312,
       2.44029516e-312, 2.35541533e-312, 6.79038654e-313, 2.35541533e-312,
       6.79038654e-313, 2.41907520e-312, 6.79038654e-313, 2.10077583e-312,
       2.48273508e-312, 2.29175545e-312, 2.10077583e-312, 2.05833592e-312])

In [115]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [116]:
np.linspace(1, 2, 11)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. ])

In [117]:
np.ones_like(b)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [118]:
np.ones(10, dtype='i2')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int16)

### Random numbers

In [119]:
np.random.randint(1, 10, (2, 20))

array([[6, 2, 1, 1, 9, 3, 7, 2, 8, 2, 8, 3, 8, 8, 3, 9, 7, 7, 7, 8],
       [1, 6, 4, 7, 7, 3, 5, 8, 6, 7, 1, 8, 8, 3, 9, 5, 3, 7, 6, 8]])

In [120]:
np.random.random((3, 4))

array([[0.19947116, 0.4571574 , 0.28163379, 0.98783017],
       [0.48776837, 0.79614873, 0.24131885, 0.46029281],
       [0.28428726, 0.85197613, 0.00926147, 0.82078925]])

In [121]:
np.random.uniform(0, 5, 10)

array([0.64218488, 1.54296547, 4.75881757, 1.74213266, 3.64732395,
       3.08299183, 1.35812761, 1.84388252, 2.68588726, 4.19049544])

## Broadcasting

In [122]:
g = np.array([1, 2, 3, 4])
h = np.array([5, 6, 7, 8])
g * h  # if the shapes match, operations are usually done element-by-element

array([ 5, 12, 21, 32])

In [123]:
g * 23  # as we have already seen, the rule relaxes when the shapes meet certain constraints

array([23, 46, 69, 92])

### Broadcasting rules
- NumPy compares the shapes element-wise, starting with the trailing dimension
- two dimensions are compatible if they are equal or one of them is __1__
- raises a `ValueError: frames are not aligned` if the shapes are incompatible
- the size of a successfully broadcasted array is the maximus size along each dimension of the input arrays

### Operation on two arrays with different shapes
```
A      (4d array):  5 x 1 x 4 x 1
B      (3d array):      7 x 1 x 5
Result (4d array):  5 x 7 x 4 x 5
```

In [5]:
arr_1 = np.array([[1, 2, 3], [4, 5, 6]])
arr_2 = np.array([[1], [2]])

print('arr_1 shape:', arr_1.shape)
print('arr_2 shape:', arr_2.shape)

arr_3 = arr_1 + arr_2
print('arr_3 shape:', arr_3.shape)

arr_3

arr_1 shape: (2, 3)
arr_2 shape: (2, 1)
arr_3 shape: (2, 3)


array([[2, 3, 4],
       [6, 7, 8]])

In [6]:
i = np.arange(20).reshape(4, 5)
i

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [7]:
describe(i)

object type: <class 'numpy.ndarray'>
size: 20
ndim: 2
shape: (4, 5)
dtype: int64


In [19]:
i * np.array([[0], [1], [2], [4]])

array([[ 0,  0,  0,  0,  0],
       [ 5,  6,  7,  8,  9],
       [20, 22, 24, 26, 28],
       [60, 64, 68, 72, 76]])

In [128]:
j = np.array([0, 10, 20, 30])
k = np.array([7, 8, 9])

In [ ]:
%shorterr j+k

In [ ]:
j[:, np.newaxis]  # inserts a new axis, making it two dimensional

In [ ]:
j[:, np.newaxis] + k

## Universal Functions (`ufunc`)

#### A `ufunc` is a "vectorized" wrapper for a function that takes a fixed number of scalar inputs and produces a fixed number of scalar outputs.

NumPy provides a bunch of `ufunc`s:
- Math operations (`add()`, `subtract()`, `square()`, `log10()`, ...)
- Trigonometric functions (`sin()`, `cos()`, `tan()`, `deg2rad()`, ...)
- Bit-twiddling functions (`bitwise_and()`, `right_shift()`, ...)
- Comparison functions (`greater()`, `less_equal()`, `fmax()`, ...)
- Floating functions (`isnan()`, `isinf()`, `floor()`, ...)
    
They all are subclasses of `np.ufunc`

In [ ]:
type(np.cos)  # they all are subclasses of np.ufunc

### Create your own `ufunc` with `np.frompyfunc(func, nin, nout)`

In [129]:
m = np.random.randint(0, 100, 17)
m

array([44, 27, 50, 66, 25, 33,  5, 65, 33, 84, 42, 53, 17, 12,  5, 77, 95])

In [130]:
def step_23(x):
    return 1 if x > 23 else 0

In [131]:
%shorterr step_23(m)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()


In [134]:
ustep_23 = np.frompyfunc(step_23, 1, 1)

In [135]:
ustep_23(m)

array([1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1], dtype=object)

## Views and Copies

In [136]:
n = np.arange(10)
n

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [137]:
o = n         # `o` will point to `n`
o[2] = 99
n             # changing `o` has changed `n`

array([ 0,  1, 99,  3,  4,  5,  6,  7,  8,  9])

In [138]:
p = n[5]      # single element access returns a copy
p

5

In [139]:
p = 9999
o             # o is not affected when `p` is changed

array([ 0,  1, 99,  3,  4,  5,  6,  7,  8,  9])

### Slices return (memory) views

In [ ]:
o= np.arange(10)
q = o[2:4]    # slices return (memory) views
q


In [ ]:
q[1] = 99  # changing elements of `o` are actual changes to `a`
o

## Acknowledgements
![](images/eu_asterics.png)

This tutorial was supported by the H2020-Astronomy ESFRI and Research Infrastructure Cluster (Grant Agreement number: 653477).